{ self, nixpkgs, ... }:

let
  system = "x86_64-linux";
  pkgs = nixpkgs.legacyPackages.${system};
  
  # Import the full initramfs patching module
  initramfsPatchingModule = import ./derivations/initramfs-patching-module.nix;
  
in {
  # Package providing the initramfs patching
  packages.${system}.initramfs-patching = pkgs.stdenv.mkDerivation {
    name = "initramfs-patching-wrapper";
    version = "1.0.0";
    
    # Native build dependencies
    nativeBuildInputs = with pkgs; [
      coreutils
    ];
    
    # Don't need to unpack since we're just creating test files
    dontUnpack = true;
    
    # Build phase - create a wrapper that points to the real implementation
    buildPhase = ''
      runHook preBuild
      
      echo "Creating initramfs patching wrapper..."
      
      # Create output directory
      mkdir -p $out
      
      # Create a metadata file explaining how to use the real implementation
      cat > $out/README.txt << EOF
      Initramfs Patching Implementation
      ================================
      
      This is a wrapper package that points to the full initramfs patching implementation.
      
      To use the full initramfs patching functionality, you need to:
      
      1. Enable the initramfs-patching NixOS module in your configuration:
         
         {
           imports = [ ${self}/flake_modules/derivations/initramfs-patching-module.nix ];
           
           initramfs-patching = {
             enable = true;
             shimBin = ./data/shim.bin;
             bootloaderFiles = ./bootloader;
             recoveryBin = ./data/recovery.bin;  # Optional
           };
         }
      
      2. Build your system with: nixos-rebuild switch
      
      3. The patched initramfs will be available at: ./patched-initramfs
      
      Available Packages:
      - initramfs-patching: The patched initramfs with bootloader
      - kernel-harvesting: Harvested kernel modules and firmware
      - kernel-repackaging: Repackaged kernel with patched initramfs
      - extracted-kernel: Extracted kernel partition
      - extracted-initramfs: Extracted initramfs from kernel
      
      Generated by: Nix derivation wrapper
      Date: $(date)
      EOF
      
      runHook postBuild
    '';
    
    # Meta information
    meta = with pkgs.lib; {
      description = "Wrapper for the full initramfs patching implementation";
      longDescription = ''
        This package serves as a wrapper and documentation for the full initramfs patching
        implementation. The actual functionality is provided by the NixOS module in
        initramfs-patching-poc/derivations/initramfs-patching-module.nix.
        
        The full implementation provides:
        - ChromeOS kernel partition extraction
        - Initramfs extraction and patching with shimboot bootloader
        - Kernel module and firmware harvesting
        - Kernel repackaging with patched initramfs
        - Complete NixOS module integration
      '';
      license = licenses.bsd3;
      platforms = platforms.linux;
      maintainers = [ "shimboot developers" ];
    };
  };
  
  # Export the full NixOS module
  nixosModules.initramfs-patching = initramfsPatchingModule;
}