{ self, nixpkgs, ... }:

let
  system = "x86_64-linux";
  pkgs = nixpkgs.legacyPackages.${system};
  
  # Create a simple test derivation that verifies the module structure
  initramfsPatchingTest = pkgs.stdenv.mkDerivation {
    name = "initramfs-patching-test";
    version = "1.0.0";
    
    # Native build dependencies
    nativeBuildInputs = with pkgs; [
      coreutils
    ];
    
    # Don't need to unpack since we're just creating test files
    dontUnpack = true;
    
    # Build phase - create test files
    buildPhase = ''
      runHook preBuild
      
      echo "Creating initramfs patching test files..."
      
      # Create output directory
      mkdir -p $out
      
      # Create a test initramfs structure
      mkdir -p $out/initramfs-test/bin
      mkdir -p $out/initramfs-test/opt
      
      # Copy bootloader files
      cp -r ${../bootloader}/* $out/initramfs-test/
      
      # Create a test script
      cat > $out/test-initramfs-patching.sh << 'EOF'
      #!/bin/sh
      echo "Initramfs patching test successful!"
      echo "Bootloader files included:"
      ls -la $(dirname $0)/initramfs-test/bin/
      ls -la $(dirname $0)/initramfs-test/opt/
      echo "Version file:"
      cat $(dirname $0)/initramfs-test/opt/.shimboot_version
      EOF
      
      chmod +x $out/test-initramfs-patching.sh
      
      # Create metadata
      cat > $out/test-metadata.txt << EOF
      Initramfs Patching Test
      =====================
      Generated by: Nix derivation
      Date: $(date)
      Bootloader files: ${../bootloader}
      
      This is a test derivation that verifies the initramfs patching module structure
      is correctly integrated into the flake.
      
      Files created:
      - test-initramfs-patching.sh: Test script
      - test-metadata.txt: This metadata file
      - initramfs-test/: Test initramfs structure with bootloader files
      EOF
      
      runHook postBuild
    '';
    
    # Meta information
    meta = with pkgs.lib; {
      description = "Test derivation for initramfs patching module";
      longDescription = ''
        This derivation provides a test framework for verifying that the initramfs patching
        module is correctly integrated into the flake structure. It creates a simple
        test initramfs structure with the bootloader files and provides a test script
        to verify the integration.
      '';
      license = licenses.bsd3;
      platforms = platforms.linux;
      maintainers = [ "shimboot developers" ];
    };
  };
  
in {
  # Package providing the initramfs patching test
  packages.${system}.initramfs-patching-test = initramfsPatchingTest;
}