# Setup Experience Module
#
# Purpose: Write system-wide Hyprland config with exec-once=kitty for setup experience
#
# The config lives at /etc/xdg/hypr/hyprland.conf (Hyprland's system config path)
# and only adds exec-once. All keybindings come from Hyprland's autogenerated defaults.
{
  lib,
  config,
  ...
}:
let
  notHeadless = !config.shimboot.headless;
in
{
  config = lib.mkIf notHeadless {
    environment.etc."xdg/hypr/hyprland.conf" = {
        text = ''
          exec-once = kitty
        '';
        mode = "0444";
      };

    programs.hyprland = {
      enable = lib.mkDefault true;
    };
  };
}
