name: build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [raw-rootfs, raw-rootfs-minimal]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_version: 2.18.1
      - uses: cachix/cachix-action@v14
        with:
          name: shimboot-systemd-nixos
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Build ${{ matrix.target }}
        run: nix build --impure --accept-flake-config .#${{ matrix.target }}