name: build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Reclaim disk space for Nix (Nothing but Nix)
      - name: Free disk space for Nix builds
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage   # maximum space freeing for large builds
          witness-carnage: true      # optional: see what it removes

      # 3️⃣ Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_version: 2.18.1
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Setup Cachix (binary cache)
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: shimboot-systemd-nixos
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # 5️⃣ Show available disk before build (optional diagnostic)
      - name: Check disk space
        run: |
          echo "💿 Disk usage before build:"
          df -h /
          df -h /nix || true
          echo "🧹 Cleaning up Docker and other space..."
          docker system prune -af || true
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true

      # 6️⃣ Build raw-rootfs-minimal
      - name: Build raw-rootfs-minimal
        run: |
          nix build --impure --accept-flake-config .#raw-rootfs-minimal
          echo "✅ Build of raw-rootfs-minimal complete!"

      # 7️⃣ Push minimal to Cachix
      - name: Push minimal to Cachix
        run: |
          cachix push shimboot-systemd-nixos ./result
          echo "✅ Pushed raw-rootfs-minimal to Cachix"

      # 8️⃣ Build raw-rootfs
      - name: Build raw-rootfs
        run: |
          nix build --impure --accept-flake-config .#raw-rootfs
          echo "✅ Build of raw-rootfs complete!"

      # 9️⃣ Push full to Cachix
      - name: Push full to Cachix
        run: |
          cachix push shimboot-systemd-nixos ./result
          echo "✅ Pushed raw-rootfs to Cachix"

      # 8️⃣ Verify artifact result and store space again
      - name: Post-Build Disk Usage
        if: always()
        run: df -h /nix