name: flake-update

on:
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 6:00 UTC
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: holster

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_version: 2.18.1

      - name: Update flake inputs
        run: nix flake update

      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          if ! git diff --quiet; then
            git switch -c flake-update-$(date +%Y%m%d)
            git add flake.lock
            git commit -m "chore: automatic flake update ($(date -u +'%Y-%m-%d'))"
            git push origin HEAD
          else
            echo "✅ No changes to flake.lock — already up to date!"
          fi

      - name: Open PR
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: flake-update-$(date +%Y%m%d)
          title: "chore: weekly flake update ($(date -u +'%Y-%m-%d'))"